# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigPopup.ui',
# licensing of 'ConfigPopup.ui' applies.
#
# Created: Sat Dec  7 18:06:35 2019
#      by: PyQt5-uic  running on PyQt5 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 353)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 6, 471, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pages = QtWidgets.QToolBox(self.gridLayoutWidget)
        self.pages.setObjectName("pages")
        self.playback_page = QtWidgets.QWidget()
        self.playback_page.setGeometry(QtCore.QRect(0, 0, 469, 271))
        self.playback_page.setObjectName("playback_page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.playback_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 411, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.playback_speed_input = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.playback_speed_input.setMinimumSize(QtCore.QSize(70, 0))
        self.playback_speed_input.setMinimum(0.1)
        self.playback_speed_input.setMaximum(2.0)
        self.playback_speed_input.setSingleStep(0.1)
        self.playback_speed_input.setProperty("value", 1.0)
        self.playback_speed_input.setObjectName("playback_speed_input")
        self.horizontalLayout.addWidget(self.playback_speed_input)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pages.addItem(self.playback_page, "")
        self.groups_page = QtWidgets.QWidget()
        self.groups_page.setGeometry(QtCore.QRect(0, 0, 469, 271))
        self.groups_page.setObjectName("groups_page")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groups_page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, -1, 411, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.group_dropdown = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.group_dropdown.setObjectName("group_dropdown")
        self.horizontalLayout_2.addWidget(self.group_dropdown)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.current_color_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.current_color_label.setObjectName("current_color_label")
        self.horizontalLayout_3.addWidget(self.current_color_label)
        self.current_color = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.current_color.setObjectName("current_color")
        self.horizontalLayout_3.addWidget(self.current_color)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.set_color_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.set_color_button.setObjectName("set_color_button")
        self.horizontalLayout_3.addWidget(self.set_color_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.pages.addItem(self.groups_page, "")
        self.gridLayout.addWidget(self.pages, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Playback Speed", None, -1))
        self.pages.setItemText(self.pages.indexOf(self.playback_page), QtWidgets.QApplication.translate("Form", "Playback", None, -1))
        self.current_color_label.setText(QtWidgets.QApplication.translate("Form", "Current Color: ", None, -1))
        self.current_color.setText(QtWidgets.QApplication.translate("Form", "(-1, -1, -1)", None, -1))
        self.set_color_button.setText(QtWidgets.QApplication.translate("Form", "Set Color", None, -1))
        self.pages.setItemText(self.pages.indexOf(self.groups_page), QtWidgets.QApplication.translate("Form", "Groups", None, -1))

